# Generated by Django 5.2 on 2025-12-21 14:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')],
                        db_index=True,
                        default='new',
                        max_length=20,
                    ),
                ),
                (
                    'priority',
                    models.IntegerField(
                        choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'
                    ),
                ),
            ],
            options={
                'db_table': 'tasks_task',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['project', 'status', '-created_at'], name='idx_task_proj_status_created'),
                    models.Index(
                        condition=models.Q(('deadline__isnull', False)), fields=['deadline'], name='idx_task_deadline'
                    ),
                    models.Index(
                        condition=models.Q(('deadline__isnull', False)),
                        fields=['deadline', 'status'],
                        name='idx_task_deadline_status',
                    ),
                    models.Index(fields=['-updated_at'], name='idx_task_updated'),
                ],
            },
        ),
    ]
