# Generated by Django 5.2 on 2025-12-24 09:13

from django.db import migrations, models


def update_new_status_to_in_progress(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task.objects.filter(status='new').update(status='in_progress')


def reverse_in_progress_to_new(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task.objects.filter(status='in_progress').update(status='new')


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            update_new_status_to_in_progress,
            reverse_in_progress_to_new,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done')], db_index=True, default='in_progress', max_length=20),
        ),
    ]
